version: '3'

services:
  bot:
    build: .
    restart: always
    depends_on:
      - mongo
    env_file:
      - ./config/.env
    volumes:
      - ./src:/app/src
      - ./config:/app/config

  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodb_data: